version: "3"

services:
  crudreacttrac:
    container_name: crudcontainer
    restart: always
    build: .
    ports: 
      - "3000:4000"
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27017:27017"